#!/bin/bash
echo "remplacement des virgules"
cp $1 $2

sed -i -n -e '/^[0-9]/p' $2
sed -i -e "s/,/./g" $2
echo "Suppression du header"
sed -i -e '1,2d' $2
echo "remplacement des tabulations"
sed -i -e "s/\t\t\t\t\t\t\t\t\t//g" $2
sed -i -e "s/\t\t\t\t\t//g" $2
sed -i -e "s/\t/,/g" $2
chmod 666 $2
#echo "remplacement des espaces"
#sed -i -e "s/ /,/g" data.txt

touch $3
chmod 777 $3
ligne=`sed -n -e '/Acquisition/=' $1`;
echo ligne = $ligne;
let fin=$ligne+2;
echo fin = $fin;

#echo $cmd;
sed -n -e "/Acquisition/,$fin p" $1 >> $3;
sed -n -e "/Acquisition/,$fin p" $1;
sed -i -e "/Acquisition/d" $3;

#sed -n -e '/Acquisition/, 2 p' $1;
#sed -n 1p $1 >> header
#sed -n 2p $1 >> header
#sed -n 3p $1 >> header

#sed -i -e "s/,/./g" header

sed -i -e "s/#//g" $3
sed -i -e "s/\t\t\t\t\t\t\t\t\t/,/g" $3
sed -i -e "s/\t\t\t\t\t\t/,/g" $3
sed -i -e "s/\t\t\t\t\t/,/g" $3
sed -i -e "s/\t/,/g" $3
sed -i -e "s/  /,/g" $3


